# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

# The ignored dependencies are so that we get open PRs that result proper nested changelogs

version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: "daily"
      time: "12:00"
    open-pull-requests-limit: 99
    ignore:
    - dependency-name: "balena-auth"
    - dependency-name: "balena-pine"
    - dependency-name: "balena-register-device"
    - dependency-name: "balena-request"
    commit-message:
      prefix: patch
    rebase-strategy: disabled
